"""Smart Diagnostic runtime configuration, unchanged from production."""
from __future__ import annotations

import os

from machinemind.config.assistant_runtime import V13_EVIDENCE_GATE_MODEL
from machinemind.config.runtime import ROOT_CAUSE_RESPONSE_MODEL

__all__ = [
    "SMART_DIAGNOSTIC_ENABLED",
    "SMART_DIAGNOSTIC_MODEL",
    "SMART_DIAGNOSTIC_MAX_QUESTIONS",
    "SMART_DIAGNOSTIC_MAX_HYPOTHESES",
    "SMART_DIAGNOSTIC_TOP_K",
    "SMART_DIAGNOSTIC_MAX_CONTEXT_CHARS",
    "SMART_DIAGNOSTIC_MAX_EVIDENCE_IN_STATE",
    "SMART_DIAGNOSTIC_SOURCE_MANIFEST_VERSION",
    "SMART_DIAGNOSTIC_FINAL_SOURCE_LIMIT",
    "SMART_DIAGNOSTIC_LLM_TIMEOUT",
    "SMART_DIAGNOSTIC_EVIDENCE_GATE_MODEL",
    "SMART_DIAGNOSTIC_EVIDENCE_GATE_TIMEOUT",
    "SMART_DIAGNOSTIC_EVIDENCE_GATE_MIN_CONFIDENCE",
    "SMART_DIAGNOSTIC_RETRIEVAL_ASSURANCE_ENABLED",
    "SMART_DIAGNOSTIC_RETRIEVAL_ASSURANCE_MAX_SECONDS_START",
    "SMART_DIAGNOSTIC_RETRIEVAL_ASSURANCE_MAX_SECONDS_ANSWER",
    "SMART_DIAGNOSTIC_RETRIEVAL_ASSURANCE_MAX_NEW_EVIDENCE",
]

SMART_DIAGNOSTIC_ENABLED = (os.environ.get("MM_SMART_DIAGNOSTIC_ENABLED") or "0").strip() == "1"
SMART_DIAGNOSTIC_MODEL = (os.environ.get("MM_SMART_DIAGNOSTIC_MODEL") or ROOT_CAUSE_RESPONSE_MODEL).strip()
SMART_DIAGNOSTIC_MAX_QUESTIONS = int(os.environ.get("MM_SMART_DIAGNOSTIC_MAX_QUESTIONS", "6"))
SMART_DIAGNOSTIC_MAX_HYPOTHESES = int(os.environ.get("MM_SMART_DIAGNOSTIC_MAX_HYPOTHESES", "4"))
SMART_DIAGNOSTIC_TOP_K = int(os.environ.get("MM_SMART_DIAGNOSTIC_TOP_K", "8"))
SMART_DIAGNOSTIC_MAX_CONTEXT_CHARS = int(os.environ.get("MM_SMART_DIAGNOSTIC_MAX_CONTEXT_CHARS", "22000"))
SMART_DIAGNOSTIC_MAX_EVIDENCE_IN_STATE = int(os.environ.get("MM_SMART_DIAGNOSTIC_MAX_EVIDENCE_IN_STATE", "8"))
SMART_DIAGNOSTIC_SOURCE_MANIFEST_VERSION = "smart-source-manifest-v1-20260831"
SMART_DIAGNOSTIC_FINAL_SOURCE_LIMIT = max(
    2,
    min(8, int(os.environ.get("MM_SMART_DIAGNOSTIC_FINAL_SOURCE_LIMIT", "6"))),
)
SMART_DIAGNOSTIC_LLM_TIMEOUT = int(os.environ.get("MM_SMART_DIAGNOSTIC_LLM_TIMEOUT_SECONDS", "70"))

# Smart Diagnostic uses the same general evidence-sufficiency principle.
# It does not recognize individual phrases or special conversational cases.
SMART_DIAGNOSTIC_EVIDENCE_GATE_MODEL = (
    os.environ.get("MM_SMART_DIAGNOSTIC_EVIDENCE_GATE_MODEL") or V13_EVIDENCE_GATE_MODEL
).strip()
SMART_DIAGNOSTIC_EVIDENCE_GATE_TIMEOUT = int(
    os.environ.get("MM_SMART_DIAGNOSTIC_EVIDENCE_GATE_TIMEOUT_SECONDS", "18")
)
SMART_DIAGNOSTIC_EVIDENCE_GATE_MIN_CONFIDENCE = float(
    os.environ.get("MM_SMART_DIAGNOSTIC_EVIDENCE_GATE_MIN_CONFIDENCE", "0.60")
)
SMART_DIAGNOSTIC_RETRIEVAL_ASSURANCE_ENABLED = (os.environ.get("MM_SMART_DIAGNOSTIC_RETRIEVAL_ASSURANCE_ENABLED") or "1").strip() != "0"
SMART_DIAGNOSTIC_RETRIEVAL_ASSURANCE_MAX_SECONDS_START = max(2, min(10, int(os.environ.get("MM_SMART_DIAGNOSTIC_RETRIEVAL_ASSURANCE_MAX_SECONDS_START", "7"))))
SMART_DIAGNOSTIC_RETRIEVAL_ASSURANCE_MAX_SECONDS_ANSWER = max(1, min(7, int(os.environ.get("MM_SMART_DIAGNOSTIC_RETRIEVAL_ASSURANCE_MAX_SECONDS_ANSWER", "4"))))
SMART_DIAGNOSTIC_RETRIEVAL_ASSURANCE_MAX_NEW_EVIDENCE = max(1, min(6, int(os.environ.get("MM_SMART_DIAGNOSTIC_RETRIEVAL_ASSURANCE_MAX_NEW_EVIDENCE", "4"))))
